#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamSoclApp
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="teamsocl")]
	public partial class SqlLINQDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public SqlLINQDataContext() : 
				base(global::TeamSoclApp.Properties.Settings.Default.teamsoclConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public SqlLINQDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SqlLINQDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SqlLINQDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SqlLINQDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<user> users
		{
			get
			{
				return this.GetTable<user>();
			}
		}
		
		public System.Data.Linq.Table<team> teams
		{
			get
			{
				return this.GetTable<team>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.users")]
	public partial class user
	{
		
		private System.Nullable<int> _uid;
		
		private string _first_name;
		
		private string _last_name;
		
		private System.Nullable<int> _roster_num;
		
		private string _nickname;
		
		private System.Nullable<bool> _admin;
		
		private System.Nullable<long> _phone;
		
		private string _email;
		
		private System.Nullable<int> _tids1;
		
		private System.Nullable<int> _tids2;
		
		private System.Nullable<int> _tids3;
		
		private System.Nullable<int> _tids4;
		
		private System.Nullable<bool> _privacy;
		
		public user()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uid", DbType="Int")]
		public System.Nullable<int> uid
		{
			get
			{
				return this._uid;
			}
			set
			{
				if ((this._uid != value))
				{
					this._uid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_first_name", DbType="VarChar(15)")]
		public string first_name
		{
			get
			{
				return this._first_name;
			}
			set
			{
				if ((this._first_name != value))
				{
					this._first_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_last_name", DbType="VarChar(15)")]
		public string last_name
		{
			get
			{
				return this._last_name;
			}
			set
			{
				if ((this._last_name != value))
				{
					this._last_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_roster_num", DbType="Int")]
		public System.Nullable<int> roster_num
		{
			get
			{
				return this._roster_num;
			}
			set
			{
				if ((this._roster_num != value))
				{
					this._roster_num = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nickname", DbType="VarChar(15)")]
		public string nickname
		{
			get
			{
				return this._nickname;
			}
			set
			{
				if ((this._nickname != value))
				{
					this._nickname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_admin", DbType="Bit")]
		public System.Nullable<bool> admin
		{
			get
			{
				return this._admin;
			}
			set
			{
				if ((this._admin != value))
				{
					this._admin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="BigInt")]
		public System.Nullable<long> phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				if ((this._phone != value))
				{
					this._phone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(35)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this._email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tids1", DbType="Int")]
		public System.Nullable<int> tids1
		{
			get
			{
				return this._tids1;
			}
			set
			{
				if ((this._tids1 != value))
				{
					this._tids1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tids2", DbType="Int")]
		public System.Nullable<int> tids2
		{
			get
			{
				return this._tids2;
			}
			set
			{
				if ((this._tids2 != value))
				{
					this._tids2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tids3", DbType="Int")]
		public System.Nullable<int> tids3
		{
			get
			{
				return this._tids3;
			}
			set
			{
				if ((this._tids3 != value))
				{
					this._tids3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tids4", DbType="Int")]
		public System.Nullable<int> tids4
		{
			get
			{
				return this._tids4;
			}
			set
			{
				if ((this._tids4 != value))
				{
					this._tids4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_privacy", DbType="Bit")]
		public System.Nullable<bool> privacy
		{
			get
			{
				return this._privacy;
			}
			set
			{
				if ((this._privacy != value))
				{
					this._privacy = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.teams")]
	public partial class team
	{
		
		private System.Nullable<int> _tid;
		
		private string _team_name;
		
		private string _coachf;
		
		private string _coachl;
		
		private System.Nullable<int> _coach_uid;
		
		public team()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tid", DbType="Int")]
		public System.Nullable<int> tid
		{
			get
			{
				return this._tid;
			}
			set
			{
				if ((this._tid != value))
				{
					this._tid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_team_name", DbType="VarChar(20)")]
		public string team_name
		{
			get
			{
				return this._team_name;
			}
			set
			{
				if ((this._team_name != value))
				{
					this._team_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_coachf", DbType="VarChar(15)")]
		public string coachf
		{
			get
			{
				return this._coachf;
			}
			set
			{
				if ((this._coachf != value))
				{
					this._coachf = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_coachl", DbType="VarChar(15)")]
		public string coachl
		{
			get
			{
				return this._coachl;
			}
			set
			{
				if ((this._coachl != value))
				{
					this._coachl = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_coach_uid", DbType="Int")]
		public System.Nullable<int> coach_uid
		{
			get
			{
				return this._coach_uid;
			}
			set
			{
				if ((this._coach_uid != value))
				{
					this._coach_uid = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
