<?xml version="1.0" encoding="utf-8"?><Database Name="teamsocl" Class="SqlLINQDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=10.33.36.70;Initial Catalog=teamsocl;User ID=sa" SettingsObjectName="TeamSoclApp.Properties.Settings" SettingsPropertyName="teamsoclConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.users" Member="users">
    <Type Name="user">
      <Column Name="uid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="first_name" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="last_name" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="roster_num" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="nickname" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="admin" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="phone" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(35)" CanBeNull="true" />
      <Column Name="tids1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tids2" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tids3" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tids4" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="privacy" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.teams" Member="teams">
    <Type Name="team">
      <Column Name="tid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="team_name" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="coachf" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="coachl" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="coach_uid" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>